List w multiple item types
android/snippets pull request #344
Opened 2024-09-13 23:00 UTC by thedmail

2024-09-15 21:18 UTC, riggaroo commented on compose/snippets/src/main/java/com/example/compose/snippets/lists/ListWithMultipleItemTypes.kt
> +    LazyColumn {
Doesn't this need the surrounding snippet comments?

2024-09-20 16:56 UTC, riggaroo requested changes
Needs surrounding tags for rendering in DAC

2024-09-23 17:34 UTC, thedmail commented on compose/snippets/src/main/java/com/example/compose/snippets/lists/ListWithMultipleItemTypes.kt
> +    LazyColumn {
Done.

2024-09-24 09:32 UTC, riggaroo approved these changes

2024-09-25 01:51 UTC, merged